spring.application.name=be
server.port=8080
server.servlet.context-path=/
spring.web.error.include-message=always


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dish}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
